### ISSUE TITLE
`tuple.flatten` throws a type error

### ISSUE THREAD

**Issue by jyn514** [jpivarski/gsoc2018-prep-problem#2]
```python
>>> ((1), (2)).flatten
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "functional.py", line 125, in flattener
    return sum(lst, [])
TypeError: can only concatenate list (not "int") to list
>>> [[1], [2]].flatten
[1, 2]
```

**Comment by davidlange6** [comment]
hi @jyn514 - this error is expected (eg, flatten works on lists of lists). Was there a specific question you were unable to implement?

**Comment by jyn514** [comment]
Yes, I was trying to pass multiple arguments to a function as a tuple, but I couldn't find a functional way to unpack the arguments. I could send the code if you're interested.
